# Generated by Django 4.0.3 on 2022-04-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ident', models.TextField()),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('latitude_deg', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitude_deg', models.DecimalField(decimal_places=17, max_digits=20)),
                ('elevation_ft', models.IntegerField()),
                ('continent', models.TextField()),
                ('iso_country', models.TextField()),
                ('iso_region', models.TextField()),
                ('municipality', models.TextField()),
                ('scheduled_service', models.TextField()),
                ('gps_code', models.TextField()),
                ('iata_code', models.TextField()),
                ('local_code', models.TextField()),
                ('home_link', models.URLField()),
                ('wikipedia_link', models.URLField()),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('numberID', models.CharField(max_length=20)),
                ('passport_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=200)),
                ('number_of_seats', models.IntegerField()),
                ('is_economy_class', models.BooleanField()),
                ('is_business_class', models.BooleanField()),
                ('is_first_class', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaneFlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=200, unique=True)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('is_delay', models.BooleanField(default=False)),
                ('delay_time_in_h', models.IntegerField(null=True)),
                ('travel_cost', models.FloatField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_airport_FK', to='base.airport')),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pilot')),
                ('plane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.plane')),
                ('to_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_airport_FK', to='base.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('numberID', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(max_length=20)),
                ('reserved_seat', models.CharField(max_length=200)),
                ('is_extra_baggage', models.BooleanField()),
                ('baggage_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.planeflights')),
            ],
        ),
    ]
