# Generated by Django 4.0.3 on 2022-04-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_planeflights_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='planeflights',
            name='status',
            field=models.IntegerField(choices=[('0', 'Cancelled'), ('1', 'Scheduled'), ('2', 'Scheduled Delayed'), ('3', 'Go to your gate'), ('4', 'Last call'), ('5', 'En Route'), ('6', 'En Route Delayed'), ('7', 'Landed'), ('8', 'Landed Delayed')], default='1', max_length=1),
        ),
    ]
