# Generated by Django 4.0.3 on 2022-06-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_planeflights_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='baggage_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='planeflights',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Scheduled'), (2, 'Scheduled Delayed'), (3, 'Go to your gate'), (4, 'Last call'), (5, 'En Route'), (6, 'En Route Delayed'), (7, 'Landed'), (8, 'Landed Delayed')]),
        ),
    ]
